Implemented the redirection

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -2,11 +2,17 @@
 # A script that transfers a file from client
 # to server
 # Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
-# if less than 3 argument, the file is sent to home
 
-if [[ $# -lt 3 ]]
+if [[ $# -lt 4 ]]
 then
-	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":"$4"
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 else
-	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
+	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3"@"$2":~/
+fi
+
+if [[ $? -eq 0 ]]
+then
+  echo "FILE WAS TRANSFERED SUCCESSFULLY"
+else
+  echo "FILE TRANSFER FAIL"
 fi
